program makeit;

uses
  Forms,
  IBData in 'IBData.pas' {dmIBData: TDataModule},
  IBModulo in 'IBModulo.pas' {dmIBModulo: TDataModule},
  menu in 'menu.pas' {frmMenu},
  reglas_de_negocios in 'reglas_de_negocios.pas',
  clases in 'clases.pas',
  autorizacion_cliente in 'autorizacion_cliente.pas' {frmAplicacionCliente},
  Ruta in 'Ruta.pas' {frRuta},
  padre in 'padre.pas' {frmPadre},
  hijo in 'hijo.pas' {frmHijo},
  explorar in 'explorar.pas' {frmExplorar},
  explorarMDI in 'explorarMDI.pas' {frmExplorarMDI},
  capturar in 'capturar.pas' {frmCapturar},
  capturarMDI in 'capturarMDI.pas' {frmCapturarMDI},
  capturar_configuracion_menu in 'capturar_configuracion_menu.pas' {frmCapturar_configuracion_menu},
  explorar_usuarios in 'explorar_usuarios.pas' {frmExplorar_Usuarios},
  UfrmAcceso in 'UfrmAcceso.pas' {frmAcceso},
  IBReportes in 'IBReportes.pas' {dmReportes: TDataModule},
  elegir_empresa in 'elegir_empresa.pas' {frmElegir_Empresa},
  acerca in 'acerca.pas' {frmAcerca},
  UfrmColaboradores in 'UfrmColaboradores.pas' {frmColaboradores},
  uMensajesError in 'uMensajesError.pas',
  autorizacion in 'autorizacion.pas' {frmAutorizacion},
  URecords in 'URecords.pas',
  UTipos in 'UTipos.pas',
  UfrmConstructor in 'UfrmConstructor.pas' {frmConstructor},
  UfrmBuild in 'UfrmBuild.pas' {frmBuild},
  UfrmScript in 'UfrmScript.pas' {frmScript},
  UAWR in 'UAWR.pas',
  CAPTURA in 'CAPTURA.pas' {frmCaptura},
  USQLAnaliza in 'USQLAnaliza.pas',
  capturar_botones in 'mConfig\capturar_botones.pas' {frmCapturar_botones},
  capturar_condiciones_comerciales in 'mcatalogos\capturar_condiciones_comerciales.pas' {frmCapturar_condiciones_comerciales},
  capturar_empresa in 'mcatalogos\capturar_empresa.pas' {frmCapturar_empresa},
  capturar_entidad_geografica in 'mcatalogos\capturar_entidad_geografica.pas' {frmCapturar_entidad_geografica},
  capturar_monedas in 'mcatalogos\capturar_monedas.pas' {frmCapturar_monedas},
  capturar_tipo_de_ctas in 'mcatalogos\capturar_tipo_de_ctas.pas' {frmCapturar_tipo_de_ctas},
  explorar_condiciones_comerciales in 'mcatalogos\explorar_condiciones_comerciales.pas' {frmExplorar_condiciones_comerciales},
  explorar_monedas in 'mcatalogos\explorar_monedas.pas' {frmExplorar_monedas},
  explorar_tipo_de_ctas in 'mcatalogos\explorar_tipo_de_ctas.pas' {frmExplorar_tipo_de_ctas},
  UfrmCFD in 'mcatalogos\UfrmCFD.pas' {frmCFD},
  UfrmValor in 'mcatalogos\UfrmValor.pas' {frmValor},
  capturar_formas_estatus in 'mConfig\capturar_formas_estatus.pas' {frmCapturar_Formas_Estatus},
  capturar_iconos_menu in 'mConfig\capturar_iconos_menu.pas' {frmCapturar_iconos_menu},
  capturar_relacion_botones in 'mConfig\capturar_relacion_botones.pas' {frmCapturar_relacion_botones},
  capturar_tipos_de_formas in 'mConfig\capturar_tipos_de_formas.pas' {frmCapturar_tipos_de_formas},
  explorar_botones in 'mConfig\explorar_botones.pas' {frmExplorar_botones},
  explorar_relacion_botones in 'mConfig\explorar_relacion_botones.pas' {frmExplorar_relacion_botones},
  explorar_tipos_de_formas in 'mConfig\explorar_tipos_de_formas.pas' {frmExplorar_tipos_de_formas},
  mantenimientoDiccionario in 'mConfig\mantenimientoDiccionario.pas' {frmMantenimientoDiccionario},
  UfrmDiccionario in 'mConfig\UfrmDiccionario.pas' {frmDiccionario},
  UfrmEstatusDestinatarios in 'mConfig\UfrmEstatusDestinatarios.pas' {frmEstatusDestinatarios},
  UfrmFormasEstatus in 'mConfig\UfrmFormasEstatus.pas' {frmFormasEstatus},
  UfrmSeleccionarUsuario in 'mConfig\UfrmSeleccionarUsuario.pas' {frmSeleccionarUsuario},
  capturar_mensajes in 'mcatalogos\capturar_mensajes.pas' {frmCapturar_mensajes},
  explorar_mensajes in 'mcatalogos\explorar_mensajes.pas' {frmExplorar_mensajes},
  explorar_zonas in 'mcatalogos\explorar_zonas.pas' {frmExplorar_zonas},
  UfrmCostosPI in 'mcatalogos\UfrmCostosPI.pas' {frmCostosPI},
  USeleccionarConceptosGastos in 'mcatalogos\USeleccionarConceptosGastos.pas' {frmSeleccionarConceptosGastos},
  capturar_tentrega in 'mcatalogos\capturar_tentrega.pas' {frmCapturar_tentrega},
  explorar_tentrega in 'mcatalogos\explorar_tentrega.pas' {frmExplorar_tentrega},
  capturar_zonas in 'mcatalogos\capturar_zonas.pas' {frmCapturar_zonas},
  UfrmSeleccionarTEntrega in 'mcatalogos\UfrmSeleccionarTEntrega.pas' {frmSeleccionarTEntrega},
  capturar_presentaciones in 'mcatalogos\capturar_presentaciones.pas' {frmCapturar_presentaciones},
  explorar_presentaciones in 'mcatalogos\explorar_presentaciones.pas' {frmExplorar_presentaciones},
  capturar_grupos_colores in 'mcatalogos\capturar_grupos_colores.pas' {frmCapturar_grupos_colores},
  capturar_colores in 'mcatalogos\capturar_colores.pas' {frmCapturar_colores},
  explorar_colores in 'mcatalogos\explorar_colores.pas' {frmExplorar_Colores},
  explorar_grupos_colores in 'mcatalogos\explorar_grupos_colores.pas' {frmExplorar_grupos_colores},
  UfrmMedidasGrupos in 'mcatalogos\UfrmMedidasGrupos.pas' {frmMedidasGrupos},
  UfrmMedidas in 'mcatalogos\UfrmMedidas.pas' {frmMedidas},
  UdmMedidas in 'mcatalogos\UdmMedidas.pas',
  UTypeMedidas in 'mcatalogos\UTypeMedidas.pas',
  capturar_conceptos_gastos in 'mcatalogos\capturar_conceptos_gastos.pas' {frmCapturar_Conceptos_Gastos},
  explorar_conceptos_gastos in 'mcatalogos\explorar_conceptos_gastos.pas' {frmExplorar_Conceptos_Gastos},
  explorar_conceptos_descuentos_nc in 'mcatalogos\explorar_conceptos_descuentos_nc.pas' {frmExplorar_Conceptos_Descuentos},
  capturar_conceptos_descuentos in 'mcatalogos\capturar_conceptos_descuentos.pas' {frmCapturar_conceptos_descuentos},
  explorar_rutas in 'mcatalogos\explorar_rutas.pas' {frmExplorar_rutas},
  capturar_rutas in 'mcatalogos\capturar_rutas.pas' {frmCapturar_rutas},
  seleccionar_extensiones in 'mcatalogos\seleccionar_extensiones.pas' {frmSeleccionar_Extensiones},
  controladorImpresora in 'mcatalogos\controladorImpresora.pas' {frmControladorImpresoras},
  capturar_nombre_lista_precios in 'mcatalogos\capturar_nombre_lista_precios.pas' {frmCapturar_nombre_lista_precios},
  PRN_0023_Lista_Precios in 'mcatalogos\PRN_0023_Lista_Precios.pas' {frmPRN_0023_Lista_Precios},
  explorar_nombre_lista_precios in 'mcatalogos\explorar_nombre_lista_precios.pas' {frmExplorar_nombre_lista_precios},
  capturar_mis_listas_de_precios in 'mcatalogos\capturar_mis_listas_de_precios.pas' {frmCapturar_mis_listas_de_precios},
  explorar_lista_precios in 'mcatalogos\explorar_lista_precios.pas' {frmExplorar_lista_precios},
  capturar_lista_precios in 'mcatalogos\capturar_lista_precios.pas' {frmCapturar_lista_precios},
  seleccionar_almacen in 'mcatalogos\seleccionar_almacen.pas' {frmSeleccionar_Almacen},
  teclado in 'mcatalogos\teclado.pas' {frmTeclado},
  seleccionar_material in 'mcatalogos\seleccionar_material.pas' {frmSeleccionar_material},
  explorar_preconfiguracion_touchScreen in 'mcatalogos\explorar_preconfiguracion_touchScreen.pas' {frmExplorar_preconfiguracion_touchScreen},
  capturar_preconfiguracion_touchscreen in 'mcatalogos\capturar_preconfiguracion_touchscreen.pas' {frmCapturar_preconfiguracion_touchScreen},
  seleccionar_material_grupos in 'mcatalogos\seleccionar_material_grupos.pas' {frmSeleccionar_material_grupos},
  capturar_grupos_materiales in 'mcatalogos\capturar_grupos_materiales.pas' {frmCapturar_grupos_materiales},
  explorar_grupos_materiales in 'mcatalogos\explorar_grupos_materiales.pas' {frmExplorar_Grupos_Materiales},
  capturar_calidades in 'mcatalogos\capturar_calidades.pas' {frmCapturar_calidades},
  explorar_calidades in 'mcatalogos\explorar_calidades.pas' {frmExplorar_Calidades},
  capturar_cajas in 'mcatalogos\capturar_cajas.pas' {frmCapturar_cajas},
  explorar_cajas in 'mcatalogos\explorar_cajas.pas' {frmExplorar_cajas},
  UfrmSeleccionarExtension in 'mcatalogos\UfrmSeleccionarExtension.pas' {frmSeleccionarExtension},
  capturar_materiales in 'mcatalogos\capturar_materiales.pas' {frmCapturar_materiales},
  lineas in 'mcatalogos\lineas.pas' {frmLineas},
  generar in 'mcatalogos\generar.pas' {frmGenerar},
  UfrmMaterial_Costos in 'mcatalogos\UfrmMaterial_Costos.pas' {frmMaterial_Costos},
  UfrmSeleccionarCGastos in 'mcatalogos\UfrmSeleccionarCGastos.pas' {frmSeleccionarCGastos},
  UfrmMMP in 'mcatalogos\UfrmMMP.pas' {frmMMP},
  UdmAutorizar in 'mcatalogos\UdmAutorizar.pas',
  UTypeAutorizar in 'mcatalogos\UTypeAutorizar.pas',
  UfrmAutorizar in 'mcatalogos\UfrmAutorizar.pas' {frmAutorizar},
  UfrmSeleccionarTarea in 'mcatalogos\UfrmSeleccionarTarea.pas' {frmSeleccionarTarea},
  UfrmSeleccionarProveedor in 'mcatalogos\UfrmSeleccionarProveedor.pas' {frmSeleccionarProveedor},
  seleccionar_unidades in 'mcatalogos\seleccionar_unidades.pas' {frmSeleccionar_Unidades},
  explorar_materiales in 'mcatalogos\explorar_materiales.pas' {frmExplorar_materiales},
  explorar_unidades in 'mcatalogos\explorar_unidades.pas' {frmExplorar_unidades},
  capturar_unidades in 'mcatalogos\capturar_unidades.pas' {frmCapturar_unidades},
  UfrmSerie in 'mcatalogos\UfrmSerie.pas' {frmSerie},
  UfrmInvSeries in 'mcatalogos\UfrmInvSeries.pas' {frmInvSeries},
  UfrmMaterialExistencias in 'mcatalogos\UfrmMaterialExistencias.pas' {frmMaterialExistencias},
  Ulineas in 'mcatalogos\Ulineas.pas' {frmLineasSub},
  UdmAltaRapidaMateriales in 'mcatalogos\UdmAltaRapidaMateriales.pas',
  UdmHorizontal in 'mcatalogos\UdmHorizontal.pas',
  UfrmLineas in 'mcatalogos\UfrmLineas.pas' {frmCapturar_Lineas},
  capturar_almacenes in 'mcatalogos\capturar_almacenes.pas' {frmCapturar_almacenes},
  UdmLineas in 'mcatalogos\UdmLineas.pas',
  UfrmFrameMaterial in 'mcatalogos\UfrmFrameMaterial.pas' {MarcoMateriales: TFrame},
  UTypeLineas in 'mcatalogos\UTypeLineas.pas',
  UfrmSeleccionarMaterialTodos in 'mcatalogos\UfrmSeleccionarMaterialTodos.pas' {frmSeleccionarMaterialTodos},
  UfrmAltaRapidaMateriales in 'mcatalogos\UfrmAltaRapidaMateriales.pas' {frmAltaRapidaMateriales},
  UfrmHorizontal in 'mcatalogos\UfrmHorizontal.pas' {frmHorizontal},
  UfrmSeleccionarMaterialCompras in 'mcatalogos\UfrmSeleccionarMaterialCompras.pas' {frmSeleccionarMaterialCompras},
  UfrmSeleccionarMaterial in 'mcatalogos\UfrmSeleccionarMaterial.pas' {frmSeleccionarMaterial},
  explorar_almacenes in 'mcatalogos\explorar_almacenes.pas' {frmExplorar_almacenes},
  capturar_promociones in 'mcatalogos\capturar_promociones.pas' {frmCapturar_promociones},
  capturar_departamentos in 'mcatalogos\capturar_departamentos.pas' {frmCapturar_departamentos},
  explorar_financiamientos in 'mcatalogos\explorar_financiamientos.pas' {frmExplorar_financiamientos},
  capturar_financiamientos in 'mcatalogos\capturar_financiamientos.pas' {frmCapturar_financiamientos},
  explorar_promociones in 'mcatalogos\explorar_promociones.pas' {frmExplorar_promociones},
  explorar_departamentos in 'mcatalogos\explorar_departamentos.pas' {frmExplorar_departamentos},
  explorar_transportistas in 'mcatalogos\explorar_transportistas.pas' {frmExplorar_transportistas},
  capturar_transportistas in 'mcatalogos\capturar_transportistas.pas' {frmCapturar_transportistas},
  explorar_remitentes in 'mcatalogos\explorar_remitentes.pas' {frmExplorar_remitentes},
  capturar_remitentes in 'mcatalogos\capturar_remitentes.pas' {frmCapturar_remitentes},
  capturar_vendedores in 'mcatalogos\capturar_vendedores.pas' {frmCapturar_vendedores},
  seleccionar_zonas in 'mcatalogos\seleccionar_zonas.pas' {frmSeleccionar_zonas},
  explorar_vendedores in 'mcatalogos\explorar_vendedores.pas' {frmExplorar_vendedores},
  capturar_compradores in 'mcatalogos\capturar_compradores.pas' {frmCapturar_compradores},
  seleccionar_zona_comprador in 'mcatalogos\seleccionar_zona_comprador.pas' {frmSeleccionar_zona_comprador},
  explorar_compradores in 'mcatalogos\explorar_compradores.pas' {frmExplorar_compradores},
  capturar_proveedores in 'mcatalogos\capturar_proveedores.pas' {frmCapturar_proveedores},
  seleccionar_bancos_proveedores in 'mcatalogos\seleccionar_bancos_proveedores.pas' {frmSeleccionar_Bancos_Proveedores},
  explorar_proveedores in 'mcatalogos\explorar_proveedores.pas' {frmExplorar_proveedores},
  capturar_bancos in 'mcatalogos\capturar_bancos.pas' {frmCapturar_bancos},
  UfrmTabulador in 'mcatalogos\UfrmTabulador.pas' {frmTabulador},
  explorar_grupos_tabulador in 'mcatalogos\explorar_grupos_tabulador.pas' {frmExplorar_grupos_tabulador},
  explorar_extensiones in 'mcatalogos\explorar_extensiones.pas' {frmExplorar_extensiones},
  capturar_clientes in 'mcatalogos\capturar_clientes.pas' {frmCapturar_clientes},
  explorar_clientes in 'mcatalogos\explorar_clientes.pas' {frmExplorar_clientes},
  UfrmSeleccionarCliente in 'mcatalogos\UfrmSeleccionarCliente.pas' {frmSeleccionarCliente},
  UfrmSeleccionarCDescuento in 'mcatalogos\UfrmSeleccionarCDescuento.pas' {frmSeleccionarCDescuento},
  UfrmSeleccionarRemitente in 'mcatalogos\UfrmSeleccionarRemitente.pas' {frmSeleccionarRemitente},
  capturar_usuarios in 'mcatalogos\capturar_usuarios.pas' {frmCapturar_usuarios},
  capturar_seguridad in 'mcatalogos\capturar_seguridad.pas' {frmCapturar_seguridad},
  capturar_activar_botones in 'mcatalogos\capturar_activar_botones.pas' {frmCapturar_activar_botones},
  capturar_base_sujetos in 'mcatalogos\capturar_base_sujetos.pas' {frmCapturar_base_sujetos},
  UfrmImagen in 'mcatalogos\UfrmImagen.pas' {frmImagen},
  seleccionar_bancos in 'mcatalogos\seleccionar_bancos.pas' {frmSeleccionar_bancos},
  seleccionar in 'mcatalogos\seleccionar.pas' {frmSeleccionar},
  capturar_grupos_tabulador in 'mcatalogos\capturar_grupos_tabulador.pas' {frmCapturar_grupos_tabulador},
  capturar_tabuladores in 'mcatalogos\capturar_tabuladores.pas' {frmCapturar_tabuladores},
  explorar_tabuladores in 'mcatalogos\explorar_tabuladores.pas' {frmExplorar_tabuladores},
  capturar_clasificaciones in 'mcatalogos\capturar_clasificaciones.pas' {frmCapturar_clasificaciones},
  explorar_clasificaciones in 'mcatalogos\explorar_clasificaciones.pas' {frmExplorar_clasificaciones},
  explorar_tabulador_nlp in 'mcatalogos\explorar_tabulador_nlp.pas' {frmExplorar_tabulador_nlp},
  explorar_bancos in 'mcatalogos\explorar_bancos.pas' {frmExplorar_bancos},
  UTypeHorizontal in 'mcatalogos\UTypeHorizontal.pas',
  UTypeAltaRapidaMateriales in 'mcatalogos\UTypeAltaRapidaMateriales.pas',
  capturar_desempaques in 'mEntradas\capturar_desempaques.pas',
  capturar_ordenes_de_compras in 'mEntradas\capturar_ordenes_de_compras.pas' {frmCapturar_Ordenes_de_Compras},
  capturar_procesos in 'mEntradas\capturar_procesos.pas' {frmCapturar_procesos},
  capturar_requisicion_cotizaciones in 'mEntradas\capturar_requisicion_cotizaciones.pas' {frmCapturar_requisicion_cotizaciones},
  capturar_requisiciones in 'mEntradas\capturar_requisiciones.pas' {frmCapturar_requisiciones},
  cotizaciones_en_ocompras in 'mEntradas\cotizaciones_en_ocompras.pas' {frmCotizaciones_en_ocompras},
  explorar_desempaques in 'mEntradas\explorar_desempaques.pas' {frmExplorar_desempaques},
  explorar_ordenes_de_compras in 'mEntradas\explorar_ordenes_de_compras.pas' {frmExplorar_ordenes_de_compras},
  explorar_requisiciones in 'mEntradas\explorar_requisiciones.pas' {frmExplorar_requisiciones},
  explorar_requisiciones_cot in 'mEntradas\explorar_requisiciones_cot.pas' {frmExplorar_requisicion_cotizaciones},
  PRN_0025 in 'mEntradas\PRN_0025.pas' {frmPRN_0025},
  seleccionar_proveedor in 'mEntradas\seleccionar_proveedor.pas' {frmSeleccionar_proveedor},
  U0002_PR in 'mEntradas\U0002_PR.pas' {PR_0002},
  UfrmFolio in 'mEntradas\UfrmFolio.pas' {frmFolio},
  UfrmSeleccionarRequisicion in 'mEntradas\UfrmSeleccionarRequisicion.pas' {frmSeleccionarRequisicion},
  UPRN_0039 in 'mEntradas\UPRN_0039.pas' {PRN_0039},
  UPRN_0050 in 'mEntradas\UPRN_0050.pas' {PRN_0050},
  capturar_pedimento_importacion in 'mEntradas\capturar_pedimento_importacion.pas' {frmCapturar_Pedimento_Importacion},
  UPRN_0040 in 'mEntradas\UPRN_0040.pas' {PRN_0040},
  explorar_pedimento_importacion in 'mEntradas\explorar_pedimento_importacion.pas' {frmExplorar_pedimento_importacion},
  UfrmSeleccionarNE in 'mEntradas\UfrmSeleccionarNE.pas' {frmSeleccionarNE},
  explorar_notas_de_entrada in 'mEntradas\explorar_notas_de_entrada.pas' {frmExplorar_notas_de_entrada},
  U0001_PR in 'mEntradas\U0001_PR.pas' {PR_0001},
  PRN_0032 in 'mEntradas\PRN_0032.pas' {frmPRN_0032},
  capturar_entradas in 'capturar_entradas.pas',
  capturarMDIEstatus in 'mEntradas\capturarMDIEstatus.pas' {frmCapturarMDIEstatus},
  explorar_cotizaciones in 'mSalidas\explorar_cotizaciones.pas' {frmExplorar_cotizaciones},
  capturar_cotizaciones in 'mSalidas\capturar_cotizaciones.pas' {frmCapturar_cotizaciones},
  explorar_cotizaciones_estatus in 'mSalidas\explorar_cotizaciones_estatus.pas',
  UfrmTLEstatus in 'mSalidas\UfrmTLEstatus.pas' {frmTLEstatus},
  seleccionar_cliente in 'mSalidas\seleccionar_cliente.pas' {frmSeleccionar_cliente},
  UfrmPresupuesto in 'mSalidas\UfrmPresupuesto.pas' {frmPresupuesto},
  UPRN_0036 in 'mSalidas\UPRN_0036.pas' {PRN_0036},
  UfrmRTF in 'mSalidas\UfrmRTF.pas' {frmRTF},
  capturar_pedidos in 'mSalidas\capturar_pedidos.pas' {frmCapturar_pedidos},
  explorar_pedidos in 'mSalidas\explorar_pedidos.pas',
  seleccionar_cotizaciones in 'mSalidas\seleccionar_cotizaciones.pas' {frmSeleccionar_cotizaciones},
  seleccionar_extension in 'mSalidas\seleccionar_extension.pas' {frmSeleccionar_extension},
  ver_cotizaciones_en_pedidos in 'mSalidas\ver_cotizaciones_en_pedidos.pas' {frmVer_Cotizaciones_en_Pedidos},
  PRN_0026 in 'mSalidas\PRN_0026.pas' {frmPRN_0026},
  PRN_0027 in 'mSalidas\PRN_0027.pas' {frmPRN_0027},
  PRN_0030 in 'mSalidas\PRN_0030.pas' {frmPRN_0030},
  URPT_PEDIDO_PARTIDAS in 'mSalidas\URPT_PEDIDO_PARTIDAS.pas' {RPT_PEDIDO_PARTIDAS},
  ufrmSeleccionarPresentaciones in 'mSalidas\ufrmSeleccionarPresentaciones.pas' {frmSeleccionarPresentaciones},
  UfrmFTP in 'mSalidas\UfrmFTP.pas' {frmFTP},
  UfrmInsuficienciasPedido in 'mSalidas\UfrmInsuficienciasPedido.pas' {frmInsuficienciasPedido},
  UfrmKit in 'mSalidas\UfrmKit.pas' {frmKit},
  UfrmSeleccionarCotizacion in 'mSalidas\UfrmSeleccionarCotizacion.pas' {frmSeleccionarCotizacion},
  capturar_facturas in 'mSalidas\capturar_facturas.pas' {frmCapturar_facturas},
  explorar_facturas in 'mSalidas\explorar_facturas.pas' {frmExplorar_Facturas},
  seleccionar_pedidos in 'mSalidas\seleccionar_pedidos.pas' {frmSeleccionar_pedidos},
  UfrmSeleccionarPedidoParaFacturas in 'mSalidas\UfrmSeleccionarPedidoParaFacturas.pas' {frmSeleccionarPedidoParaFacturas},
  UfrmInsuficienciasFactura in 'mSalidas\UfrmInsuficienciasFactura.pas' {frmInsuficienciasFactura},
  UfrmFacturasGastos in 'mSalidas\UfrmFacturasGastos.pas' {frmFacturasGastos},
  UfrmElegirCFF in 'mSalidas\UfrmElegirCFF.pas' {frmCFF},
  PRN_0003_FACTURAR in 'mSalidas\PRN_0003_FACTURAR.pas' {frmPRN_0003},
  PRN_0003_FACTURAR_TXT in 'mSalidas\PRN_0003_FACTURAR_TXT.pas' {frmPRN_0003_TXT},
  UdmNCreditoAlta in 'mSalidas\UdmNCreditoAlta.pas' {dmNCreditoAlta: TDataModule},
  UfrmNCreditoAlta in 'mSalidas\UfrmNCreditoAlta.pas' {frmNCreditoAlta},
  PRN_0012_Facturacion in 'mSalidas\PRN_0012_Facturacion.pas' {frmPRN_0012},
  ver_pedidos_en_facturas in 'mSalidas\ver_pedidos_en_facturas.pas' {frmVer_Pedidos_en_Facturas},
  frmBusqueda in 'mSalidas\frmBusqueda.pas' {fmBusquedas},
  frmConsultaVentasAnteriores in 'mSalidas\frmConsultaVentasAnteriores.pas' {fmConsultaVentasAnteriores},
  UfrmGuiaEmbarque in 'mSalidas\UfrmGuiaEmbarque.pas' {frmGuiaDeEmbarque},
  PRN_0028 in 'mSalidas\PRN_0028.pas' {frmPRN_0028},
  UPRN_0041 in 'mSalidas\UPRN_0041.pas' {PRN_0041},
  UPRN_0042 in 'mSalidas\UPRN_0042.pas' {PRN_0042},
  capturar_despachador in 'mSalidas\capturar_despachador.pas' {frmCapturar_Despachador},
  explorar_despachador in 'mSalidas\explorar_despachador.pas' {frmExplorar_Despachador},
  UfrmDespachador in 'mSalidas\UfrmDespachador.pas' {frmDespachador},
  UfrmCambioPrecio in 'mSalidas\UfrmCambioPrecio.pas' {frmCambioPrecio},
  explorar_surtimiento in 'mSalidas\explorar_surtimiento.pas' {frmExplorar_surtimiento},
  UfrmSurtimiento in 'mSalidas\UfrmSurtimiento.pas' {frmSurtimiento},
  UfrmSurtimientoUsuarioDe in 'mSalidas\UfrmSurtimientoUsuarioDe.pas' {frmSurtimientoUsuarioDe},
  PRN_0029_MI in 'mSalidas\PRN_0029_MI.pas' {frmPRN_0029},
  UfrmDespachadorSurtimiento in 'mSalidas\UfrmDespachadorSurtimiento.pas' {frmDespachadorSurtimiento},
  UfrmInsuficienciasSurtimiento in 'mSalidas\UfrmInsuficienciasSurtimiento.pas' {frmInsuficienciasSurtimiento},
  UfrmSurtimientoListaEmpaque in 'mSalidas\UfrmSurtimientoListaEmpaque.pas' {frmSurtimientoListaEmpaque},
  UfrmCarteleraAlmacen in 'mSalidas\UfrmCarteleraAlmacen.pas' {frmCarteleraAlmacen},
  PRN_0027_A in 'mSalidas\PRN_0027_A.pas' {frmPRN_0027_A},
  UTypeNCreditoAlta in 'mSalidas\UTypeNCreditoAlta.pas',
  explorar_punto_de_ventas in 'mSalidas\explorar_punto_de_ventas.pas' {frmExplorar_punto_de_ventas},
  capturar_punto_de_ventas in 'mSalidas\capturar_punto_de_ventas.pas' {frmCapturar_punto_de_ventas},
  explorar_punto_de_ventas_reporteador in 'mSalidas\explorar_punto_de_ventas_reporteador.pas' {frmExplorar_punto_de_ventas_rep},
  capturar_punto_de_ventas_pagos in 'mSalidas\capturar_punto_de_ventas_pagos.pas' {frmCapturar_punto_de_ventas_pagos},
  UfrmInfo in 'mSalidas\UfrmInfo.pas' {frmInfo},
  PRN_0008_Ventas in 'mSalidas\PRN_0008_Ventas.pas' {frmPRN_0008},
  ver_detalle_venta in 'mSalidas\ver_detalle_venta.pas' {frmVerDetalleHijo},
  UfrmValesDetalle in 'mSalidas\UfrmValesDetalle.pas' {frmValesDetalle},
  PRN_0034 in 'mSalidas\PRN_0034.pas' {frmPRN_0034},
  UfrmMonederoReg in 'mSalidas\UfrmMonederoReg.pas' {frmMonederoReg},
  UMarcoTNumerico in 'mSalidas\UMarcoTNumerico.pas' {MarcoTNumerico: TFrame},
  UfrmPOSEfectivo in 'mSalidas\UfrmPOSEfectivo.pas' {frmPOSEfectivo},
  teclado_numerico in 'mSalidas\teclado_numerico.pas' {frmTeclado_Numerico},
  PRN_0004_NOTA_VENTA_TXT in 'mSalidas\PRN_0004_NOTA_VENTA_TXT.pas' {frmPRN_0004_TXT},
  PRN_0004_NOTA_VENTA in 'mSalidas\PRN_0004_NOTA_VENTA.pas' {frmPRN_0004},
  PRN_CORTE_CAJAS_PV in 'mSalidas\PRN_CORTE_CAJAS_PV.pas' {frmPRN_CORTE_CAJA_PV},
  RPT_FICHA_DEPOSITO in 'mSalidas\RPT_FICHA_DEPOSITO.pas' {frmRPT_FICHA_DEPOSITO},
  RPT_CORTE_CAJAS_PV in 'mSalidas\RPT_CORTE_CAJAS_PV.pas' {frmRPT_CORTE_CAJAS_PV},
  RPT_CORTE_CAJAS_DET_PV in 'mSalidas\RPT_CORTE_CAJAS_DET_PV.pas' {frmRPT_CORTE_CAJAS_DET_PV},
  RPT_CORTE_CAJAS_CC_PV in 'mSalidas\RPT_CORTE_CAJAS_CC_PV.pas' {frmRPT_CORTE_CAJAS_CC_PV},
  RPT_CORTE_CAJAS_CC_DET_PV in 'mSalidas\RPT_CORTE_CAJAS_CC_DET_PV.pas' {frmRPT_CORTE_CAJAS_CC_DET_PV},
  RPT_RESUMEN_ALMACENES in 'mSalidas\RPT_RESUMEN_ALMACENES.pas' {frmRPT_RESUMEN_ALMACENES},
  RPT_ENTRADAS_SALIDAS in 'mSalidas\RPT_ENTRADAS_SALIDAS.pas' {frmRPT_ENTRADAS_SALIDAS},
  RPT_CORTE_CAJAS_CAJAS in 'mSalidas\RPT_CORTE_CAJAS_CAJAS.pas' {frmRPT_CORTE_CAJAS_CAJAS},
  PRN_CAJAS_DEVOLUCIONES in 'mSalidas\PRN_CAJAS_DEVOLUCIONES.pas' {frmPRN_CAJAS_DEVOLUCIONES},
  UfrmPOSPagos in 'mSalidas\UfrmPOSPagos.pas' {frmPOSPagos},
  UfrmPOSTC in 'mSalidas\UfrmPOSTC.pas' {frmPOSTC},
  UfrmPOSVales in 'mSalidas\UfrmPOSVales.pas' {frmPOSVales},
  capturar_punto_de_venta_cancelacion in 'mSalidas\capturar_punto_de_venta_cancelacion.pas' {frmCapturar_Punto_de_Venta_Cancelacion},
  UPRN_0037_PVTAS in 'mSalidas\UPRN_0037_PVTAS.pas' {PRN_0037},
  capturar_devoluciones in 'mSalidas\capturar_devoluciones.pas' {frmCapturar_Devoluciones},
  UfrmConsultaPrecios in 'mSalidas\UfrmConsultaPrecios.pas' {frmConsultaPrecios},
  AltaRapidaCliente in 'mSalidas\AltaRapidaCliente.pas' {frmAltaRapidaCliente},
  UfrmBasculaPuerto in 'mSalidas\UfrmBasculaPuerto.pas' {frmBasculaPuerto},
  UfrmSeleccionarPedidoParaPOS in 'mSalidas\UfrmSeleccionarPedidoParaPOS.pas' {frmSeleccionarPedidoParaPOS},
  UfrmColectas in 'mSalidas\UfrmColectas.pas' {frmColectas},
  PRN_0006_Colectas in 'mSalidas\PRN_0006_Colectas.pas' {frmPRN_0006},
  UfrmF12Imp in 'mSalidas\UfrmF12Imp.pas' {frmF12Imp},
  capturar_cxp_movimientos in 'mFinanzas\capturar_cxp_movimientos.pas' {frmCapturar_cxp_movimientos},
  capturar_cxp_pagos in 'mFinanzas\capturar_cxp_pagos.pas' {frmCapturar_CXP_FormasDePago},
  PRN_0017_ESTADOS_CXP in 'mFinanzas\PRN_0017_ESTADOS_CXP.pas' {frmPRN_0017},
  PRN_0035 in 'mFinanzas\PRN_0035.pas' {frmPRN_0035},
  PRN_CORTE_CAJAS_CXP in 'mFinanzas\PRN_CORTE_CAJAS_CXP.pas' {frmPRN_CORTE_CAJAS_CXP},
  RPT_CORTE_CAJAS_CXP in 'mFinanzas\RPT_CORTE_CAJAS_CXP.pas' {frmRPT_CORTE_CAJAS_CXP},
  RPT_CORTE_CAJAS_CXP_CC in 'mFinanzas\RPT_CORTE_CAJAS_CXP_CC.pas' {frmRPT_CORTE_CAJAS_CXP_CC},
  RPT_CORTE_CAJAS_CXP_CC_DET in 'mFinanzas\RPT_CORTE_CAJAS_CXP_CC_DET.pas' {frmRPT_CORTE_CAJAS_CXP_CC_DET},
  RPT_CORTE_CAJAS_CXP_DET in 'mFinanzas\RPT_CORTE_CAJAS_CXP_DET.pas' {frmRPT_CORTE_CAJAS_CXP_DET},
  UCXP_PagosD in 'mFinanzas\UCXP_PagosD.pas' {frmCXP_PagosD},
  UdmCuentasPorPagar in 'mFinanzas\UdmCuentasPorPagar.pas' {dmCuentasPorPagar: TDataModule},
  UdmDetalleDeLaCompra in 'mFinanzas\UdmDetalleDeLaCompra.pas' {dmDetalleDeLaCompra: TDataModule},
  UdmDocumentoNCargoAfectada in 'mFinanzas\UdmDocumentoNCargoAfectada.pas' {dmDocumentoNCargoAfectada: TDataModule},
  UdmDocumentoNCargoSAfectar in 'mFinanzas\UdmDocumentoNCargoSAfectar.pas' {dmDocumentoNCargoSAfectar: TDataModule},
  UdmDocumentoNCreditoAfectada in 'mFinanzas\UdmDocumentoNCreditoAfectada.pas' {dmDocumentoNCreditoAfectada: TDataModule},
  UdmDocumentoNCreditoSAfectar in 'mFinanzas\UdmDocumentoNCreditoSAfectar.pas' {dmDocumentoNCreditoSAfectar: TDataModule},
  UdmDocumentoPagosCXP in 'mFinanzas\UdmDocumentoPagosCXP.pas' {dmDocumentoPagosCXP: TDataModule},
  UfrmCuentasPorPagar in 'mFinanzas\UfrmCuentasPorPagar.pas' {frmCuentasPorPagar},
  UfrmDetalleDeLaCompra in 'mFinanzas\UfrmDetalleDeLaCompra.pas' {frmDetalleDeLaCompra},
  UfrmDocumentoNCargoAfectada in 'mFinanzas\UfrmDocumentoNCargoAfectada.pas' {frmDocumentoNCargoAfectada},
  UfrmDocumentoNCargoSAfectar in 'mFinanzas\UfrmDocumentoNCargoSAfectar.pas' {frmDocumentoNCargoSAfectar},
  UfrmDocumentoNCreditoAfectada in 'mFinanzas\UfrmDocumentoNCreditoAfectada.pas' {frmDocumentoNCreditoAfectada},
  UfrmDocumentoNCreditoSAfectar in 'mFinanzas\UfrmDocumentoNCreditoSAfectar.pas' {frmDocumentoNCreditoSAfectar},
  UfrmDocumentoPagosCXP in 'mFinanzas\UfrmDocumentoPagosCXP.pas' {frmDocumentoPagosCXP},
  UfrmSeleccionarProveedor_ in 'mFinanzas\UfrmSeleccionarProveedor_.pas' {frmSeleccionarProveedor_},
  Uprn_0003 in 'mFinanzas\Uprn_0003.pas' {PRN_0003},
  UTypeDetalleDeLaCompra in 'mFinanzas\UTypeDetalleDeLaCompra.pas',
  UTypeDocumentoNCargoAfectada in 'mFinanzas\UTypeDocumentoNCargoAfectada.pas',
  UTypeDocumentoNCargoSAfectar in 'mFinanzas\UTypeDocumentoNCargoSAfectar.pas',
  UTypeDocumentoNCreditoAfectada in 'mFinanzas\UTypeDocumentoNCreditoAfectada.pas',
  UTypeDocumentoNCreditoSAfectar in 'mFinanzas\UTypeDocumentoNCreditoSAfectar.pas',
  UTypeDocumentoPagosCXP in 'mFinanzas\UTypeDocumentoPagosCXP.pas',
  UTypeCuentasPorPagar in 'UTypeCuentasPorPagar.pas',
  Uprn_0004 in 'mFinanzas\Uprn_0004.pas' {PRN_0004};

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TdmIBModulo, dmIBModulo);
  Application.CreateForm(TdmIBData, dmIBData);
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.Run;
end.
